receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
  awsecscontainermetrics:
    collection_interval: 10s

processors:
  filter:
    metrics:
      include:
        match_type: strict
        metric_names:
          - ecs.task.memory.utilized
          - ecs.task.memory.reserved
          - ecs.task.cpu.utilized
          - ecs.task.cpu.reserved
          - ecs.task.network.rate.rx
          - ecs.task.network.rate.tx
          - ecs.task.storage.read_bytes
          - ecs.task.storage.write_bytes
  
  batch:

exporters:
  prometheusremotewrite:
    endpoint: <YOUR-APS-WORKSPACE-ENDPOINT>/api/v1/remote_write
    auth:
      authenticator: sigv4auth
  awsxray:
   region: us-east-1
  logging:
    loglevel: debug

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679
  sigv4auth:
    region: us-east-1 
    
service:
  extensions: [pprof, zpages, health_check, sigv4auth]
  pipelines:
    traces:
      receivers:  [otlp]
      processors: [batch]
      exporters:  [awsxray]
    metrics:
      receivers:  [otlp]
      processors: [batch]
      exporters:  [prometheusremotewrite]
    # metrics/ecs:
    #   receivers:  [awsecscontainermetrics]
    #   processors: [filter]
    #   exporters:  [logging, prometheusremotewrite]